fixtures:
  symlinks:
    etckeeper: "#{source_dir}"
    test: "#{source_dir}/spec/fixtures/test"
  forge_modules:
    inifile:
      repo: "puppetlabs/inifile"
      ref: "5.0.1"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "7.1.0"
